resources:
- name: repo
  type: git
  source:
    uri: https://github.com/walidaouane/test-pipeline-concourse.git
    branch: main
jobs:
- name: hello-world-job
  plan:
  - get: repo
    trigger: true   # tell Concourse to trigger this job when new versions are emitted
  - task: hello-world-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      inputs: # add the get step as an input to this task
      - name: repo
      run: # read the file from the get step
        path: cat
        args: ["repo/README.md"]