resources:
- name: repo
  type: git
  source:
    uri: git@github.com:walidaouane/test-pipeline-concourse.git
    branch: main
jobs:
- name: hello-world-job2
  plan:
  - get: repo
    trigger: true   # tell Concourse to trigger this job when new versions are emitted
  - task: hello-world-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      run:
        path: echo
        args: ["Hello World!"]