resources:
- name: repo
  type: git
  source:
    uri: git@github.com:walidaouane/test-pipeline-concourse.git
    branch: main
    private_key: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
      NhAAAAAwEAAQAAAYEArBD0GpFgtIGVj76tEhwE9n6YNLna5w2fakYZDbVV7HMH/8ymWlGS
      MlpLu7N4bfTlyDal2iql5lyRjtEvOUx6XKDD7pJ3GCnX5sGDpVXWo5om+xH0imyxDMwL62
      Hml7JV/VdZ3RZK4XOVosjDu9LZTQx/R9OSdiYA7SMMs6tKlRMo4vIS2sVLR6Q0ybAl1v+f
      MuTB8hJalTeyLmr9T8GeFK8erWSQh4CZM6HLnW8JPl0JEFrZbVKOOqxMtR1KxbLp82OyQZ
      xOmPwcuIvyuJE2cVRBgZx5kbv0ytP76kbw4LfoxsAcVoLrBs0IfW2aS4w8oWZhhlnU7Mg/
      hY6zhH4E5bZZSJwVf185+e8e0JdRF/lAOSgfmuog6HvNGHDoJwoFn6w+je4PAOVD/Cr6os
      kEZK+935OWONXNZth36hcAKg2UJwkv6G4MJfT/P4S2DkkAlYrWcKUi++pXCioePVZTX3M3
      WqJS6miXOOJhjwqdE/Ztysyp5Al8JQ8NffF8onafAAAFiLDSM36w0jN+AAAAB3NzaC1yc2
      EAAAGBAKwQ9BqRYLSBlY++rRIcBPZ+mDS52ucNn2pGGQ21VexzB//MplpRkjJaS7uzeG30
      5cg2pdoqpeZckY7RLzlMelygw+6Sdxgp1+bBg6VV1qOaJvsR9IpssQzMC+th5peyVf1XWd
      0WSuFzlaLIw7vS2U0Mf0fTknYmAO0jDLOrSpUTKOLyEtrFS0ekNMmwJdb/nzLkwfISWpU3
      si5q/U/BnhSvHq1kkIeAmTOhy51vCT5dCRBa2W1SjjqsTLUdSsWy6fNjskGcTpj8HLiL8r
      iRNnFUQYGceZG79MrT++pG8OC36MbAHFaC6wbNCH1tmkuMPKFmYYZZ1OzIP4WOs4R+BOW2
      WUicFX9fOfnvHtCXURf5QDkoH5rqIOh7zRhw6CcKBZ+sPo3uDwDlQ/wq+qLJBGSvvd+Tlj
      jVzWbYd+oXACoNlCcJL+huDCX0/z+Etg5JAJWK1nClIvvqVwoqHj1WU19zN1qiUupolzji
      YY8KnRP2bcrMqeQJfCUPDX3xfKJ2nwAAAAMBAAEAAAGAWjV9NNyY/amedsE5zW/BLlYKiE
      IUQOSEelwL0IMMbC2WuQZbBKkVY66xW9PoxIULXx8/bpTDa3WGnoCPKJQu5pcmgdJp+9Ic
      Lg+wbCMHp7guzZyJP3VikVn8ucgW89r8eBiutVl1oqNNhQ2KiNMvN9TgehCzDZw5ChpBE4
      UvUd68pdbSCb48DHBLeJ4QCJr1pOIHyFjVArwzf2B6M7FHpoJ1K+S4XUIPj+E4de57wyVV
      lix7J3SLurkQcjfMNr/oSWkP85HyzaOlDZftkvjTUyR6MPsuNJcQhDDtonlkFC0s1AJ3uA
      7tOJPhKpWD5gNi8pTj/6xfl55RHa/40zaGZfEWxvgswic7wxU7XQ7pnVMgaNDk2ayCOZVm
      axQhlC2M5M6pmGlI0WyAOyuNbYJ/yWsEbrcFTLTY5j2bnvfFPi92A5rOrS/djJhMvfrRyR
      ebXHiBi/64LBp5xXnNwWU5vUHqVXmqbhT341KhhUviPsKB+utvqFQLpGfmIVDK90FJAAAA
      wGa05a2ZH/t7SvcNiyEz86Ie/N4LCLT7FmHsPm2q0c6HHIRqRJGD4wk5RX1yVN7R6OwpTb
      qI/1KhM/jLWc5m+AzDOqHB6D6TbNNuJHhM5PgxSFCnSdA6rYkyEGjcV+oseOetnE33/4Kr
      wXuuJLILEKQNEgP2HF0nh7819knD/vKxk3mRvWBwnmp2smpwQTr3fbtpNpB2gAMmeHdBWw
      TeJ27kPwNkjScw4KlAR5+r64P/GPUs6OsQgKLDAj4eq+ZW9AAAAMEA3KVo5XF3MU8svOR+
      PP+wONvUHv8jTbExhBELwaMxF3J71hnRII3SIelbb0Uuc/F/8Z0w3CTzIqlq1QwFGr97QY
      5qz2jvzjaTyi0cRjCvstl9ZdJOuuaitE0gqePIS7l5vN9bOLQKHan6foUgy8gxKGhIeal6
      FkfyoKxRm4MmCvZxtp3BS6bjrbHdGJ/nlwKHYnkvRT8drDBFg5jAo+F19x6SOrDHLHlg6L
      LJiTsGtiCr5ffOwm2AnAHNTADBbfN7AAAAwQDHot153eMsOu2xoZM7jmC8dE32Ry7Df/ZP
      5Iy5we2RGSF/+i8HNOc+/YwAF+CEUWRrAHpL3M4HvR3H/psMFfuB5rtxYHrFA9uofVzok4
      I6D4ryBcZsxTaG6wsNfIMH/QIYwwzPhiQ//a3xs8O0B6134Qq0mxg9goKSU5Cpd1n0Qh3K
      FUym6CydzNmy52avaefhMZoFzrtyNDtTHb5JRZLy3WYiIGlnQcn4RzinXL68wHcSAnj6G5
      G7Qh4CbXRe3i0AAAAOd2FsaWRAd2FsaWQtdm0BAgMEBQ==
      -----END OPENSSH PRIVATE KEY-----
jobs:
- name: hello-world-job
  plan:
  - get: repo
    trigger: true   # tell Concourse to trigger this job when new versions are emitted
  - task: hello-world-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      run:
        path: echo
        args: ["Hello World!"]