resources:
- name: repo
  type: git
  source:
    uri: git@github.com:walidaouane/test-pipeline-concourse.git
    branch: main
    private_key: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
      QyNTUxOQAAACCocq8JkwNy5411ohxWYipZSq4WiyVslT8p9cxmtHP0sgAAAJh+YokOfmKJ
      DgAAAAtzc2gtZWQyNTUxOQAAACCocq8JkwNy5411ohxWYipZSq4WiyVslT8p9cxmtHP0sg
      AAAEC8jCSVwwdY/p2bxwUVRwu7tCrxAPn0JKA///Q5dSoSYahyrwmTA3LnjXWiHFZiKllK
      rhaLJWyVPyn1zGa0c/SyAAAAFXdhbGlkOTEuaW5mQGdtYWlsLmNvbQ==
      -----END OPENSSH PRIVATE KEY-----
jobs:
- name: hello-world-job2
  plan:
  - get: repo
    trigger: true   # tell Concourse to trigger this job when new versions are emitted
  - task: hello-world-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      run:
        path: echo
        args: ["Hello World!"]